version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: elomux_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: elomux_db
      POSTGRES_USER: elomux_user
      POSTGRES_PASSWORD: elomux_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
